apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "supabase.storage.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.storage.environment | nindent 2 }}
