{{- if .Values.storage.persistence.enable -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "supabase.storage.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
  {{- with .Values.storage.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.storage.persistence.storageClassName }}
  storageClassName: {{ .Values.storage.persistence.storageClassName }}
  {{- end }}
  accessModes:
  {{- range .Values.storage.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.persistence.size | quote }}
{{- end }}