{{- if .Values.kong.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "supabase.kong.serviceAccountName" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
  {{- with .Values.kong.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
