apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "supabase.realtime.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.realtime.environment | nindent 2 }}
