apiVersion: v1
kind: Service
metadata:
  name: {{ include "supabase.realtime.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  type: {{ .Values.realtime.service.type }}
  ports:
    - port: {{ .Values.realtime.service.port }}
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    {{- include "supabase.realtime.selectorLabels" . | nindent 4 }}
