{{- if .Values.realtime.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "supabase.realtime.serviceAccountName" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
  {{- with .Values.realtime.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
