apiVersion: v1
kind: Service
metadata:
  name: {{ include "supabase.rest.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  type: {{ .Values.rest.service.type }}
  ports:
    - port: {{ .Values.rest.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "supabase.rest.selectorLabels" . | nindent 4 }}
