apiVersion: v1
kind: Service
metadata:
  name: {{ include "supabase.meta.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  type: {{ .Values.meta.service.type }}
  ports:
    - port: {{ .Values.meta.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "supabase.meta.selectorLabels" . | nindent 4 }}
