name: supabase_quickstart
description: Sample app on how to get started with iEchor on Flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^0.8.4
  supabase_flutter: ^1.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

flutter:
  uses-material-design: true
