name: Autofix Linting Checks

on:
  pull_request:
    types:
      - labeled

# Cancel old builds on new commit for same workflow + branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  autofix:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    permissions:
      contents: write
    if: ${{ github.event_name == 'pull_request' && (github.event.label.name == 'autofix') }}
    steps:
      - name: Calculate number of commits
        run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> "${GITHUB_ENV}"

      - name: Generate token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.GH_AUTOFIX_APP_ID }}
          private-key: ${{ secrets.GH_AUTOFIX_PRIVATE_KEY }}
          permission-contents: write

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: ${{ env.PR_FETCH_DEPTH }}
          sparse-checkout: |
            packages
            apps

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        name: Install pnpm

      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238  # v6.2.0
        with:
          node-version-file: '.nvmrc'
          cache: pnpm

      - name: Install required dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Prettier in fix mode
        run: pnpm run format

      - name: Commit changes and push to existing branch
        uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5.2.0
        with:
          commit_message: 'ci: Autofix updates from GitHub workflow'
          commit_user_name: 'kevcodez'
          commit_user_email: 'k.grueneberg1994@gmail.com'
