name: reviewdog
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

# Cancel old builds on new commit for same workflow + branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  misspell:
    name: runner / misspell
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: Check out code.
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
      - name: misspell
        uses: reviewdog/action-misspell@9daa94af4357dddb6fd3775de806bc0a8e98d3e4 # v1.26.3
        with:
          github_token: ${{ secrets.github_token }}
          locale: 'US'
          reporter: github-pr-review
          level: error
          exclude: |
            *.css
            **/package.json
            **/pnpm-lock.yaml
            ./.git/*
            *.ipynb
            ./i18n/README.*.md
            ./studio/public/monaco-editor/*
