name: '[Docs] Sync troubleshooting guides to GitHub Discussions'

on:
  push:
    branches:
      - master
    paths:
      - 'apps/docs/content/troubleshooting/**'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-troubleshooting:
    runs-on: blacksmith-4vcpu-ubuntu-2404

    env:
      DOCS_GITHUB_APP_ID: ${{ secrets.SEARCH_GITHUB_APP_ID }}
      DOCS_GITHUB_APP_INSTALLATION_ID: ${{ secrets.SEARCH_GITHUB_APP_INSTALLATION_ID }}
      DOCS_GITHUB_APP_PRIVATE_KEY: ${{ secrets.SEARCH_GITHUB_APP_PRIVATE_KEY }}
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SEARCH_SUPABASE_URL }}
      SUPABASE_SECRET_KEY: ${{ secrets.SEARCH_SUPABASE_SERVICE_ROLE_KEY }}

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          sparse-checkout: |
            apps/docs

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        name: Install pnpm
        with:
          run_install: false

      - name: Use Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238  # v6.2.0
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Troubleshooting script
        run: pnpm run --filter docs troubleshooting:sync

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # v7.0.5
        with:
          commit-message: '[bot] sync troubleshooting guides to db'
          title: '[bot] sync troubleshooting guides to db'
          author: 'github-docs-sync-bot <github-docs-sync-bot@supabase.com>'
          branch: 'bot/docs-sync-troubleshooting'
          branch-suffix: 'random'
          labels: 'documentation'
