name: '[Docs] Sync troubleshooting guides to GitHub Discussions'

on:
  push:
    branches:
      - master
    paths:
      - 'apps/docs/content/troubleshooting/**'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-troubleshooting:
    runs-on: blacksmith-4vcpu-ubuntu-2404

    env:
      DOCS_GITHUB_APP_ID: ${{ secrets.SEARCH_GITHUB_APP_ID }}
      DOCS_GITHUB_APP_INSTALLATION_ID: ${{ secrets.SEARCH_GITHUB_APP_INSTALLATION_ID }}
      DOCS_GITHUB_APP_PRIVATE_KEY: ${{ secrets.SEARCH_GITHUB_APP_PRIVATE_KEY }}
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SEARCH_SUPABASE_URL }}
      SUPABASE_SECRET_KEY: ${{ secrets.SEARCH_SUPABASE_SERVICE_ROLE_KEY }}

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          sparse-checkout: |
            apps/docs

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        name: Install pnpm
        with:
          run_install: false

      - name: Use Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Troubleshooting script
        run: pnpm run --filter docs troubleshooting:sync

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0  # v8.1.0
        with:
          commit-message: '[bot] sync troubleshooting guides to db'
          title: '[bot] sync troubleshooting guides to db'
          author: 'github-docs-sync-bot <github-docs-sync-bot@supabase.com>'
          branch: 'bot/docs-sync-troubleshooting'
          branch-suffix: 'random'
          labels: 'documentation'
