name: Snapshot Tests

on:
  pull_request:
    paths:
      - 'studio/tests/snapshot/**'
      - '.github/workflows/snapshot_tests.yml'
      - '.github/workflows/publish_docker_hub.yml'

jobs:
  snapshot-tests:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: studio

    steps:
      - name: Checkout github repo (+ lfs dependencies)
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup dependencies
        run: |
          npm ci
          npm run build
          (npm run start &)
          npx playwright install --with-deps

      - name: Run tests
        run: npm run test:snapshots:ci

      - uses: actions/upload-artifact@v1
        if: ${{ always() }}
        with:
          name: snapshot-test-results
          path: studio/test-results
